aws.globals:
  tags:
    cost_center: CIT
    Environment: Dev
  region: us-east-1
  sec_group: sg-87ce2dfe
  availability_zone: us-east-1e
plugin.cnamer:
  region: 'us-east-1'
  instances:
    -
      instanceId: i-0123456
      cname: 'example.org'
      active: true
    -
      instanceId: i-012345a
      cname: 'app.example.org'
      active: false
plugin.sns-hook:
  gitHubOrgName: OrgName
  oAuthToken: token
  snsHook:
    events:
      - push
    name: amazonsns
    config:
      sns_topic: 'arn'
      aws_secret: 'secret'
      aws_key: 'key'
    active: true
